"""
Competency 2500 SHARP 4.0 Pipeline (Async)
==========================================
Upgrades every question in competency_2500.js to full SHARP 4.0 debriefs using AsyncIO.
"""

import json, os, re, time, warnings, asyncio
warnings.filterwarnings("ignore")

from google import genai
from google.genai import types

print("Connecting to Vertex AI...")
client = genai.Client(vertexai=True, project="sih-mcq-pipeline", location="us-central1")
print("✅ Vertex AI — Gemini 2.5 Flash ready (Async)\n")

FILE_PATH   = "/Users/dr.moh/Documents/SIH/sih_project/js/questions/competency_2500.js"
CHECKPOINT  = "/Users/dr.moh/Documents/SIH/sih_project/sharp4_checkpoint.json"
SAVE_EVERY  = 50
CONCURRENCY = 20

def load_questions():
    with open(FILE_PATH, "r", encoding="utf-8") as f:
        content = f.read()
    match = re.search(r'\[\s*\{.*\}\s*\]', content, re.DOTALL)
    if match:
        return json.loads(match.group(0))
    return []

def save_questions(questions):
    header = (
        "// Auto-generated by sharp4_pipeline.py\n"
        "// Source: Competency-Based 2500 MCQs in Surgery — U. Santosh Pai (CBS, 2022)\n"
        f"// Total: {len(questions)} questions | SHARP 4.0 Enriched\n"
        "// SHARP 4.0: Imaging Pearl + Guideline Anchor + One-Line Takeaway + Difficulty\n"
        "if(!window.QUESTIONS) window.QUESTIONS = [];\n"
        f"window.QUESTIONS.push(...{json.dumps(questions, indent=2, ensure_ascii=False)});\n"
    )
    with open(FILE_PATH, "w", encoding="utf-8") as f:
        f.write(header)

def load_checkpoint():
    if os.path.exists(CHECKPOINT):
        with open(CHECKPOINT, "r") as f:
            return set(json.load(f))
    return set()

def save_checkpoint(done_ids):
    with open(CHECKPOINT, "w") as f:
        json.dump(sorted(list(done_ids)), f)

def build_prompt(q):
    lines = [
        "You are an expert surgical board examiner and data extraction AI.",
        "You are given a question from a medical databank.",
        "Write a SHARP 4.0 debrief based on the provided answer.",
        "",
        f"QUESTION:\n{q.get('question', '')}",
        "",
        f"OPTIONS:\n{json.dumps(q.get('options', {}), indent=2)}",
        "",
        f"VERIFIED ANSWER:\n{q.get('verified_answer', '')} - {q.get('answer', '')}",
        "",
        "Return ONLY a JSON object with these exact keys. Use \\n for newlines within strings. No literal line breaks.",
        "{",
        '  "status": "ACCEPT",',
        '  "set_the_stage": "<2-3 sentences: restate the verdict and explain WHY this answer is correct — the clinical/anatomical logic>",',
        '  "highlight_excellence": "<3-5 sentences: the surgical mechanism, anatomical basis, or physiology that makes the answer correct>",',
        '  "address_gaps": "<For each WRONG option write: Option X (Incorrect): [why wrong in 1-2 sentences]. Separate with \\n>",',
        '  "review_learning_points": "<A markdown table comparing 3-4 related items. Must include | header | header | format>",',
        '  "plan": "Board Pearl: <one memorable exam heuristic under 20 words>",',
        '  "imaging_intraoperative_pearl": "<What you would see on CT/X-ray/US/endoscopy OR in the OR for this topic>",',
        '  "guideline_anchor": "<Name the most relevant society guideline with year. State what it recommends>",',
        '  "takeaway": "<One memorable line under 20 words. Make it witty and impossible to forget>"',
        "}"
    ]
    return "\n".join(lines)

def safe_parse(text):
    if not text: return None
    try: return json.loads(text)
    except: pass
    
    cleaned = re.sub(r"^```(?:json)?\s*", "", text.strip())
    cleaned = re.sub(r"\s*```$", "", cleaned)
    try: return json.loads(cleaned)
    except: pass
    
    try:
        m = re.search(r"\{[\s\S]*\}", cleaned)
        if m: return json.loads(m.group(0))
    except: pass
    
    try:
        fixed = re.sub(r'(?<!\\)\n(?=[^"]*")', r"\\n", cleaned)
        return json.loads(fixed)
    except: pass
    
    return None

def build_markdown(q, p):
    tw = p.get("takeaway", "")
    sts = p.get("set_the_stage", "").replace("\\n", "\n")
    he = p.get("highlight_excellence", "").replace("\\n", "\n")
    ag = p.get("address_gaps", "").replace("\\n", "\n")
    rl = p.get("review_learning_points", "").replace("\\n", "\n")
    pl = p.get("plan", "").replace("\\n", "\n")
    img = p.get("imaging_intraoperative_pearl", "").replace("\\n", "\n")
    gl = p.get("guideline_anchor", "").replace("\\n", "\n")
    va = p.get("verified_answer", q.get("verified_answer", "?"))
    vat = p.get("verified_answer_text", q.get("answer", ""))
    diff = p.get("difficulty", "Medium")
    
    opts = q.get("options", {})
    rows = "\n".join(f"| {k} | {v[:75]} | {'✅ Correct' if k == va else '❌ Incorrect'} |" for k, v in opts.items())

    return f"### SHARP 4.0 Cognitive & Surgical Debrief\n\n> **💡 {tw}**\n\n---\n\n## S — Set the Stage\n{sts}\n\n## H — Highlight Excellence\n{he}\n\n## A — Address the Gaps\n\n{ag}\n\n## R — Review Learning Points\n\n{rl}\n\n## P — Plan (Board Pearl)\n{pl}\n\n---\n\n## 🔬 Imaging & Intraoperative Pearl\n{img}\n\n## 📋 Guideline Anchor\n{gl}\n\n---\n\n### Answer Breakdown\n| Option | Text | Status |\n|--------|------|--------|\n{rows}\n\n**✅ Answer: {va}) {vat}** &nbsp;|&nbsp; **Difficulty: {diff}** &nbsp;|&nbsp; **Source: Competency 2500**\n"

async def enrich_one(q, semaphore):
    async with semaphore:
        prompt = build_prompt(q)
        for attempt in range(2):
            try:
                resp = await client.aio.models.generate_content(
                    model="gemini-2.5-flash",
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        response_mime_type="application/json",
                        temperature=0.15,
                        max_output_tokens=2500,
                    )
                )
                payload = safe_parse(resp.text)
                if payload and payload.get("status", "").upper() in ("ACCEPT", "ACCEPTED", "OK", "VERIFIED"):
                    return payload
            except Exception as e:
                await asyncio.sleep(1 + attempt)
        return None

async def main():
    print("=" * 65)
    print("  Phase 2: Extract & SHARP 4.0 Enrichment — Competency 2500 (ASYNC)")
    print("=" * 65)
    
    questions  = load_questions()
    done_ids   = load_checkpoint()
    total      = len(questions)
    
    # Track questions by ID for O(1) updating
    q_map = {str(q.get("id")): q for q in questions}
    
    pending = [q for q in questions if str(q.get("id")) not in done_ids and "See textbook" not in q.get("answer", "")]
    
    print(f"  Total questions : {total}")
    print(f"  Already done    : {len(done_ids)}")
    print(f"  To process      : {len(pending)}")
    print(f"  Skipped (no ans): {total - len(done_ids) - len(pending)}")
    
    if not pending:
        print("✅ All done!")
        return
        
    start_time = time.time()
    enriched = 0
    failed = 0
    processed = 0
    
    semaphore = asyncio.Semaphore(CONCURRENCY)
    
    print(f"\n🚀 Starting async processing with concurrency {CONCURRENCY}...\n")
    
    async def process_task(q):
        nonlocal enriched, failed, processed
        qid = str(q["id"])
        payload = await enrich_one(q, semaphore)
        
        if payload:
            md = build_markdown(q, payload)
            va = payload.get("verified_answer", "")
            vat = payload.get("verified_answer_text", "")
            
            q_map[qid]["markdown_debrief"] = md
            q_map[qid]["difficulty"] = payload.get("difficulty", "Medium")
            if va:
                q_map[qid]["verified_answer"] = va
                q_map[qid]["answer"] = f"{va}) {vat}"
            enriched += 1
        else:
            q_map[qid]["markdown_debrief"] = "Failed to generate Markdown."
            failed += 1
            
        done_ids.add(qid)
        processed += 1
        
        if processed % SAVE_EVERY == 0:
            final_qs = list(q_map.values())
            save_questions(final_qs)
            save_checkpoint(done_ids)
            
            elapsed = time.time() - start_time
            rate = processed / elapsed if elapsed > 0 else 1
            eta = (len(pending) - processed) / rate / 60
            print(f"  💾 Saved [{len(done_ids)}/{total}] | ✅ {enriched} ❌ {failed} | Rate: {rate:.1f} Q/s | ETA: {eta:.0f} min")

    tasks = [process_task(raw) for raw in pending]
    await asyncio.gather(*tasks)

    # Final Save
    final_qs = list(q_map.values())
    save_questions(final_qs)
    save_checkpoint(done_ids)
        
    print(f"\n✅ Finished! Enriched {enriched}, Failed {failed}.")

if __name__ == "__main__":
    asyncio.run(main())
