"""
SHARP 4.0 Enrichment Pipeline
==============================
Upgrades every question in competency_2500.js from basic placeholder
debriefs to full SHARP 4.0 Cognitive & Surgical Debriefs using Gemini 2.5 Flash.

SHARP 4.0 adds over SHARP 3.0:
  ✅ S – Set the Stage (Verdict + Diagnostic Pivot)
  ✅ H – Highlight Excellence (Surgical Why + Pathophysiology)
  ✅ A – Address the Gaps (Full distractor demolition, each option explained)
  ✅ R – Review Learning Points (Comparison table + evidence framework)
  ✅ P – Plan for Improvement (Board Pearl + exam heuristic)
  🆕 I – Imaging & Intraoperative Pearl (NEW in 4.0)
  🆕 G – Guideline Anchor (Named guideline + year, NEW in 4.0)
  🆕 T – Takeaway in One Line (Tweet-length memorization hook, NEW in 4.0)

Run: python3 sharp4_pipeline.py
Output: js/questions/competency_2500.js (updated in-place)
"""

import json, os, re, time, threading
from concurrent.futures import ThreadPoolExecutor, as_completed

print("Loading Vertex AI client...")
from google import genai
from google.genai import types
import warnings
warnings.filterwarnings("ignore")

client = genai.Client(vertexai=True, project="sih-mcq-pipeline", location="us-central1")
print("✅ Vertex AI connected — Gemini 2.5 Flash ready\n")

# ── Config ────────────────────────────────────────────────────────────────────
INPUT_FILE  = "js/questions/competency_2500.js"
OUTPUT_FILE = "js/questions/competency_2500.js"
CHECKPOINT  = "sharp4_checkpoint.json"
MAX_WORKERS = 4        # Parallel threads
BATCH_SIZE  = 20       # Questions per save checkpoint
RATE_LIMIT  = 0.5      # Seconds between requests per thread

file_lock = threading.Lock()

# ── SHARP 4.0 Prompt ─────────────────────────────────────────────────────────
SHARP4_PROMPT = """You are a world-class surgical educator, board examiner, and clinical teacher.

Your task: Write a complete SHARP 4.0 Cognitive & Surgical Debrief for the MCQ below.

MCQ:
Question: {question}
Options:
  A) {A}
  B) {B}
  C) {C}
  D) {D}
Answer Key: {answer}
Chapter: {chapter}
Specialty: {specialty}

SHARP 4.0 FORMAT — Return ONLY this JSON, no extra text:
{{
  "status": "ACCEPT",
  "verified_answer": "<single letter A/B/C/D>",
  "verified_answer_text": "<full text of the correct option>",
  "set_the_stage": "<2-3 sentences: restate the verdict, explain the diagnostic pivot — WHY this is the answer, what clinical logic locks it in>",
  "highlight_excellence": "<3-5 sentences: the surgical/anatomical/physiological MECHANISM that makes the answer correct. Include the pathophysiology chain. Be precise and educational>",
  "address_gaps": "<For EACH wrong option (A, B, C, D — skip the correct one), write 1-2 sentences explaining exactly WHY it is wrong. Label each: 'Option X (Incorrect): ...' Format as a single string with newlines between each>",
  "review_learning_points": "<Build a 3-5 row comparison or classification table in Markdown format with column headers, comparing related conditions, classifications, or management steps relevant to this question>",
  "plan": "<The Board Pearl: ONE memorable exam heuristic. Start with 'Board Pearl:' — give the pattern/trigger word that maps to this answer>",
  "imaging_intraoperative_pearl": "<NEW in 4.0> What would you see on imaging (X-ray/CT/US/endoscopy) OR in the operating room relevant to this question? Be specific: describe the finding, the view, the name of the sign if one exists>",
  "guideline_anchor": "<NEW in 4.0> Cite the most relevant society guideline (e.g., ACS, ASCRS, WSES, ESMO, ACOG, BSS, NICE) with guideline name and most recent year. State what it recommends relevant to this question. If no specific guideline, cite the most authoritative textbook chapter>",
  "takeaway": "<NEW in 4.0> One-line memorization hook. Must be under 25 words. Witty, precise, and impossible to forget. Format as a bold statement>",
  "difficulty": "<Easy|Medium|Hard|Very Hard — based on the specificity and clinical reasoning required>"
}}"""

# ── Load questions ─────────────────────────────────────────────────────────────
def load_questions():
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        content = f.read()
    # Strip the JS wrapper
    m = re.search(r"window\.QUESTIONS\.push\(\.\.\.(.*)\);", content, re.DOTALL)
    if not m:
        raise ValueError("Could not parse question array from JS file")
    return json.loads(m.group(1))

# ── Save questions ─────────────────────────────────────────────────────────────
def save_questions(questions):
    header = (
        "// Auto-generated by sharp4_pipeline.py\n"
        "// Source: Competency-Based 2500 MCQs in Surgery — U. Santosh Pai (CBS, 2022)\n"
        f"// Total: {len(questions)} questions | SHARP 4.0 Enriched\n"
        "// SHARP 4.0 adds: Imaging Pearl, Guideline Anchor, One-Line Takeaway\n"
        "if(!window.QUESTIONS) window.QUESTIONS = [];\n"
        f"window.QUESTIONS.push(...{json.dumps(questions, indent=2, ensure_ascii=False)});\n"
    )
    with file_lock:
        with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
            f.write(header)

# ── Load checkpoint ────────────────────────────────────────────────────────────
def load_checkpoint():
    if os.path.exists(CHECKPOINT):
        with open(CHECKPOINT, "r") as f:
            return set(json.load(f))
    return set()

def save_checkpoint(done_ids):
    with file_lock:
        with open(CHECKPOINT, "w") as f:
            json.dump(list(done_ids), f)

# ── Build markdown_debrief from SHARP 4.0 payload ────────────────────────────
def build_markdown(q, payload):
    va  = payload.get("verified_answer", "?")
    vat = payload.get("verified_answer_text", "")
    sts = payload.get("set_the_stage", "")
    he  = payload.get("highlight_excellence", "")
    ag  = payload.get("address_gaps", "")
    rl  = payload.get("review_learning_points", "")
    pl  = payload.get("plan", "")
    img = payload.get("imaging_intraoperative_pearl", "")
    gl  = payload.get("guideline_anchor", "")
    tw  = payload.get("takeaway", "")
    diff= payload.get("difficulty", "Medium")

    opts = q.get("options", {})
    opt_rows = "\n".join(
        f"| {k} | {v[:70]} | {'✅ Correct' if k == va else '❌ Incorrect'} |"
        for k, v in opts.items()
    )

    return f"""### SHARP 4.0 Cognitive & Surgical Debrief

> **{tw}**

---

## S — Set the Stage
{sts}

## H — Highlight Excellence
{he}

## A — Address the Gaps
{ag}

## R — Review Learning Points
{rl}

## P — Plan (Board Pearl)
{pl}

---

## 🔬 I — Imaging & Intraoperative Pearl *(New in SHARP 4.0)*
{img}

## 📋 G — Guideline Anchor *(New in SHARP 4.0)*
{gl}

---

### Answer Summary
| Option | Text | Status |
|--------|------|--------|
{opt_rows}

**Verified Answer: {va}) {vat}** | **Difficulty: {diff}** | **Chapter: {q.get('chapter', '')}**
"""

# ── Enrich a single question ───────────────────────────────────────────────────
def enrich_question(q):
    opts = q.get("options", {})
    prompt = SHARP4_PROMPT.format(
        question  = q.get("question", ""),
        A = opts.get("A", ""),
        B = opts.get("B", ""),
        C = opts.get("C", ""),
        D = opts.get("D", ""),
        answer    = q.get("answer", ""),
        chapter   = q.get("chapter", ""),
        specialty = q.get("specialty", "General Surgery"),
    )

    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                temperature=0.15,
                max_output_tokens=2048,
            )
        )
        text = response.text.strip()
        # Strip markdown wrappers if any
        text = re.sub(r"^```json\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
        payload = json.loads(text)

        if payload.get("status", "").upper() not in ("ACCEPT", "ACCEPTED", "OK", "VERIFIED"):
            return None

        return payload
    except Exception as e:
        return None

# ── Main pipeline ──────────────────────────────────────────────────────────────
def main():
    print("=" * 60)
    print("  SHARP 4.0 Enrichment Pipeline")
    print("  Source: Competency-Based 2500 MCQs in Surgery")
    print("=" * 60)

    questions = load_questions()
    done_ids  = load_checkpoint()
    total     = len(questions)
    pending   = [q for q in questions if str(q.get("id")) not in done_ids]

    print(f"\n📊 Total questions : {total}")
    print(f"✅ Already done    : {len(done_ids)}")
    print(f"⏳ To enrich       : {len(pending)}")
    print(f"🧵 Workers         : {MAX_WORKERS}")
    print(f"💾 Checkpoint file : {CHECKPOINT}\n")

    if not pending:
        print("All questions already enriched! ✅")
        return

    enriched_count = 0
    failed_count   = 0
    batch_count    = 0

    def process(q):
        nonlocal enriched_count, failed_count, batch_count
        time.sleep(RATE_LIMIT)  # Rate limit per thread

        qid = str(q.get("id"))
        payload = enrich_question(q)

        if payload:
            md = build_markdown(q, payload)
            with file_lock:
                # Update the question in-place
                for i, orig in enumerate(questions):
                    if str(orig.get("id")) == qid:
                        questions[i]["markdown_debrief"] = md
                        questions[i]["difficulty"]       = payload.get("difficulty", "Medium")
                        questions[i]["verified_answer"]  = payload.get("verified_answer")
                        # Update answer if pipeline found discrepancy
                        va = payload.get("verified_answer")
                        vat = payload.get("verified_answer_text", "")
                        if va:
                            questions[i]["answer"] = f"{va}) {vat}"
                        break

                done_ids.add(qid)
                enriched_count += 1
                batch_count    += 1

                # Save checkpoint every BATCH_SIZE questions
                if batch_count % BATCH_SIZE == 0:
                    save_questions(questions)
                    save_checkpoint(done_ids)
                    pct = (len(done_ids) / total) * 100
                    print(f"  💾 Checkpoint saved — {len(done_ids)}/{total} ({pct:.1f}%) enriched")
        else:
            with file_lock:
                failed_count += 1
                done_ids.add(qid)  # Mark as done to skip on retry

        return qid

    print("🚀 Starting enrichment...\n")
    start_time = time.time()

    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = {executor.submit(process, q): q for q in pending}
        for i, future in enumerate(as_completed(futures)):
            qid = future.result()
            if (i + 1) % 50 == 0:
                elapsed = time.time() - start_time
                rate    = (i + 1) / elapsed
                remaining = (len(pending) - i - 1) / rate if rate > 0 else 0
                print(f"  Progress: {i+1}/{len(pending)} | "
                      f"Rate: {rate:.1f} Q/s | "
                      f"ETA: {remaining/60:.1f} min | "
                      f"✅ {enriched_count} OK | ❌ {failed_count} fail")

    # Final save
    save_questions(questions)
    save_checkpoint(done_ids)

    elapsed = time.time() - start_time
    print(f"\n{'='*60}")
    print(f"✅ SHARP 4.0 Enrichment Complete!")
    print(f"   Enriched : {enriched_count}")
    print(f"   Failed   : {failed_count}")
    print(f"   Time     : {elapsed/60:.1f} minutes")
    print(f"   Output   : {OUTPUT_FILE}")
    print(f"{'='*60}")

if __name__ == "__main__":
    main()
