// Auto-generated by Consolidation Script
if(typeof window !== "undefined") {
  window.QUESTIONS = window.QUESTIONS || [];
  window.QUESTIONS.push(...[
  {
    "id": 46,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "A 35-year-old woman has a breast mass that disappears after aspiration of clear fluid. The diagnosis is:",
    "options": {
      "A": "Fibroadenoma",
      "B": "Fibrocystic disease",
      "C": "Breast cancer",
      "D": "Lipoma",
      "E": "Galactocele"
    },
    "answer": "B",
    "explanation": {
      "correct": "Fibrocystic change often presents with symptomatic cysts. Aspiration of clear or straw-colored fluid with complete resolution of the mass is diagnostic of a simple cyst.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 47,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "The most common benign breast tumor in young women is:",
    "options": {
      "A": "Breast cyst",
      "B": "Intraductal papilloma",
      "C": "Fibroadenoma",
      "D": "Phylloides tumor",
      "E": "Lipoma"
    },
    "answer": "C",
    "explanation": {
      "correct": "Fibroadenomas are common, rubbery, mobile, benign tumors typically found in women in their 20s and 30s.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 49,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "A painful breast mass appearing several weeks after trauma with skin retraction is likely:",
    "options": {
      "A": "Inflammatory carcinoma",
      "B": "Hematoma",
      "C": "Abscess",
      "D": "Fat necrosis",
      "E": "Sclerosing adenosis"
    },
    "answer": "D",
    "explanation": {
      "correct": "Fat necrosis can mimic breast cancer by presenting as a firm, fixed mass with skin tethering/retraction following an injury.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 51,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "Mondor's disease of the breast refers to:",
    "options": {
      "A": "A malignant phylloides tumor",
      "B": "Lymphatic obstruction by cancer",
      "C": "Superficial thrombophlebitis",
      "D": "A fungal infection",
      "E": "Nipple inversion"
    },
    "answer": "C",
    "explanation": {
      "correct": "Mondor's disease is a benign, self-limiting superficial thrombophlebitis of the breast or chest wall veins, often appearing as a painful 'cord'.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 52,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "The most common cause of bloody nipple discharge is:",
    "options": {
      "A": "Intraductal papilloma",
      "B": "Paget's disease",
      "C": "Ductal carcinoma in situ",
      "D": "Fat necrosis",
      "E": "Fibrocystic disease"
    },
    "answer": "A",
    "explanation": {
      "correct": "While malignancy must be ruled out, a benign intraductal papilloma is the single most frequent cause of spontaneous bloody nipple discharge.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 54,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "Which mammographic finding is most likely to be benign?",
    "options": {
      "A": "Stellate mass",
      "B": "Fine pleomorphic calcifications",
      "C": "Coarse 'popcorn' calcifications",
      "D": "New architectural distortion",
      "E": "Skin thickening"
    },
    "answer": "C",
    "explanation": {
      "correct": "Coarse, 'popcorn-like' calcifications are characteristic of an involuting (calcifying) fibroadenoma and are benign.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 55,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "Which of the following is NOT a proven risk factor for breast cancer?",
    "options": {
      "A": "Smoking",
      "B": "Family history in a first-degree relative",
      "C": "Atypical ductal hyperplasia (ADH)",
      "D": "Increasing age",
      "E": "Early menarche"
    },
    "answer": "A",
    "explanation": {
      "correct": "While smoking is harmful, its status as an independent risk factor for breast cancer is less established than age, genetics, and hormonal exposure.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 57,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "In postmenopausal women with ER+ breast cancer, the most effective hormonal therapy is:",
    "options": {
      "A": "Tamoxifen",
      "B": "Raloxifene",
      "C": "Aromatase inhibitors",
      "D": "Progesterone",
      "E": "Estrogen"
    },
    "answer": "C",
    "explanation": {
      "correct": "Aromatase inhibitors (e.g., anastrozole, letrozole) have been shown to be superior to tamoxifen in postmenopausal women.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 58,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "The most important prognostic factor in breast cancer is:",
    "options": {
      "A": "Tumor size",
      "B": "Histological grade",
      "C": "Axillary lymph node status",
      "D": "ER/PR status",
      "E": "Patient age"
    },
    "answer": "C",
    "explanation": {
      "correct": "The presence and number of axillary lymph node metastases remain the single best predictor of overall survival and recurrence risk.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 61,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "Paget\u2019s disease of the nipple is characterized by:",
    "options": {
      "A": "A benign skin rash",
      "B": "Association with underlying carcinoma",
      "C": "Rapid healing with topical steroids",
      "D": "Absence of nipple biopsy findings",
      "E": "Association with Paget's disease of the bone"
    },
    "answer": "B",
    "explanation": {
      "correct": "Paget\u2019s disease presents as an eczematous change of the nipple and is almost always associated with an underlying DCIS or invasive cancer.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 62,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "A breast cancer patient with positive supraclavicular nodes is classified as:",
    "options": {
      "A": "Stage IIA",
      "B": "Stage IIIB",
      "C": "Stage IIIC",
      "D": "Stage IV",
      "E": "Stage IIB"
    },
    "answer": "C",
    "explanation": {
      "correct": "Supraclavicular lymph node involvement (N3) without distant visceral metastasis is Stage IIIC.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 66,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "The most frequent site of distant metastasis for breast cancer is:",
    "options": {
      "A": "Brain",
      "B": "Bone",
      "C": "Lung",
      "D": "Liver",
      "E": "Adrenal glands"
    },
    "answer": "B",
    "explanation": {
      "correct": "The skeleton (bone) is the most common site of distant spread for breast cancer.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 68,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "Breast cancer during pregnancy is:",
    "options": {
      "A": "Always a reason for termination",
      "B": "Never treated with chemotherapy",
      "C": "The most common cancer diagnosed during pregnancy",
      "D": "Always ER positive",
      "E": "Treated with radiation in the first trimester"
    },
    "answer": "C",
    "explanation": {
      "correct": "Breast cancer is the most common malignancy during pregnancy. Treatment depends on the trimester; chemotherapy can often be given safely in the 2nd and 3rd trimesters.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 69,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "Routine follow-up after breast cancer treatment should always include:",
    "options": {
      "A": "Monthly tumor markers",
      "B": "Quarterly CT scans",
      "C": "Yearly bone scans",
      "D": "Regular clinical exams and yearly mammography",
      "E": "Semi-annual MRI"
    },
    "answer": "D",
    "explanation": {
      "correct": "Evidence-based follow-up focuses on history, physical examination, and annual mammography to detect local recurrence or a new primary.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 70,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "Submuscular placement of breast implants is preferred because:",
    "options": {
      "A": "It is less painful.",
      "B": "It prevents all capsule formation.",
      "C": "It allows better mammographic visualization of breast tissue.",
      "D": "It is cheaper.",
      "E": "It eliminates the risk of rupture."
    },
    "answer": "C",
    "explanation": {
      "correct": "Placing implants behind the pectoral muscle makes it easier for radiologists to visualize native breast tissue during screening mammography.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 71,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "What is the incidence of breast cancer in males?",
    "options": {
      "A": "<1% of all breast cancers",
      "B": "5%",
      "C": "10%",
      "D": "20%",
      "E": "50%"
    },
    "answer": "A",
    "explanation": {
      "correct": "Male breast cancer is rare, representing less than 1% of the total breast cancer cases.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 73,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "A large breast tumor with skin erosion and a favorable outlook is likely:",
    "options": {
      "A": "Medullary carcinoma",
      "B": "Cystosarcoma phyllodes (benign)",
      "C": "Scirrhous carcinoma",
      "D": "Inflammatory carcinoma",
      "E": "Paget's disease"
    },
    "answer": "B",
    "explanation": {
      "correct": "Phyllodes tumors can grow quite large and even ulcerate the skin, but most are benign or low-grade and have an excellent prognosis with wide local excision.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 75,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "An 'occult' primary breast cancer typically presents as:",
    "options": {
      "A": "A large palpable mass",
      "B": "Nipple discharge only",
      "C": "Axillary lymphadenopathy with no visible breast mass",
      "D": "Bone pain",
      "E": "Skin rash"
    },
    "answer": "C",
    "explanation": {
      "correct": "Occult primary breast cancer presents as metastatic disease (usually in the axillary nodes) where the primary tumor in the breast cannot be identified by physical exam or standard imaging.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  }
]);
} else {
  module.exports = [
  {
    "id": 46,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "A 35-year-old woman has a breast mass that disappears after aspiration of clear fluid. The diagnosis is:",
    "options": {
      "A": "Fibroadenoma",
      "B": "Fibrocystic disease",
      "C": "Breast cancer",
      "D": "Lipoma",
      "E": "Galactocele"
    },
    "answer": "B",
    "explanation": {
      "correct": "Fibrocystic change often presents with symptomatic cysts. Aspiration of clear or straw-colored fluid with complete resolution of the mass is diagnostic of a simple cyst.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 47,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "The most common benign breast tumor in young women is:",
    "options": {
      "A": "Breast cyst",
      "B": "Intraductal papilloma",
      "C": "Fibroadenoma",
      "D": "Phylloides tumor",
      "E": "Lipoma"
    },
    "answer": "C",
    "explanation": {
      "correct": "Fibroadenomas are common, rubbery, mobile, benign tumors typically found in women in their 20s and 30s.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 49,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "A painful breast mass appearing several weeks after trauma with skin retraction is likely:",
    "options": {
      "A": "Inflammatory carcinoma",
      "B": "Hematoma",
      "C": "Abscess",
      "D": "Fat necrosis",
      "E": "Sclerosing adenosis"
    },
    "answer": "D",
    "explanation": {
      "correct": "Fat necrosis can mimic breast cancer by presenting as a firm, fixed mass with skin tethering/retraction following an injury.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 51,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "Mondor's disease of the breast refers to:",
    "options": {
      "A": "A malignant phylloides tumor",
      "B": "Lymphatic obstruction by cancer",
      "C": "Superficial thrombophlebitis",
      "D": "A fungal infection",
      "E": "Nipple inversion"
    },
    "answer": "C",
    "explanation": {
      "correct": "Mondor's disease is a benign, self-limiting superficial thrombophlebitis of the breast or chest wall veins, often appearing as a painful 'cord'.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 52,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "The most common cause of bloody nipple discharge is:",
    "options": {
      "A": "Intraductal papilloma",
      "B": "Paget's disease",
      "C": "Ductal carcinoma in situ",
      "D": "Fat necrosis",
      "E": "Fibrocystic disease"
    },
    "answer": "A",
    "explanation": {
      "correct": "While malignancy must be ruled out, a benign intraductal papilloma is the single most frequent cause of spontaneous bloody nipple discharge.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 54,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "Which mammographic finding is most likely to be benign?",
    "options": {
      "A": "Stellate mass",
      "B": "Fine pleomorphic calcifications",
      "C": "Coarse 'popcorn' calcifications",
      "D": "New architectural distortion",
      "E": "Skin thickening"
    },
    "answer": "C",
    "explanation": {
      "correct": "Coarse, 'popcorn-like' calcifications are characteristic of an involuting (calcifying) fibroadenoma and are benign.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 55,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "Which of the following is NOT a proven risk factor for breast cancer?",
    "options": {
      "A": "Smoking",
      "B": "Family history in a first-degree relative",
      "C": "Atypical ductal hyperplasia (ADH)",
      "D": "Increasing age",
      "E": "Early menarche"
    },
    "answer": "A",
    "explanation": {
      "correct": "While smoking is harmful, its status as an independent risk factor for breast cancer is less established than age, genetics, and hormonal exposure.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 57,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "In postmenopausal women with ER+ breast cancer, the most effective hormonal therapy is:",
    "options": {
      "A": "Tamoxifen",
      "B": "Raloxifene",
      "C": "Aromatase inhibitors",
      "D": "Progesterone",
      "E": "Estrogen"
    },
    "answer": "C",
    "explanation": {
      "correct": "Aromatase inhibitors (e.g., anastrozole, letrozole) have been shown to be superior to tamoxifen in postmenopausal women.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 58,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "The most important prognostic factor in breast cancer is:",
    "options": {
      "A": "Tumor size",
      "B": "Histological grade",
      "C": "Axillary lymph node status",
      "D": "ER/PR status",
      "E": "Patient age"
    },
    "answer": "C",
    "explanation": {
      "correct": "The presence and number of axillary lymph node metastases remain the single best predictor of overall survival and recurrence risk.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 61,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "Paget\u2019s disease of the nipple is characterized by:",
    "options": {
      "A": "A benign skin rash",
      "B": "Association with underlying carcinoma",
      "C": "Rapid healing with topical steroids",
      "D": "Absence of nipple biopsy findings",
      "E": "Association with Paget's disease of the bone"
    },
    "answer": "B",
    "explanation": {
      "correct": "Paget\u2019s disease presents as an eczematous change of the nipple and is almost always associated with an underlying DCIS or invasive cancer.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 62,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "A breast cancer patient with positive supraclavicular nodes is classified as:",
    "options": {
      "A": "Stage IIA",
      "B": "Stage IIIB",
      "C": "Stage IIIC",
      "D": "Stage IV",
      "E": "Stage IIB"
    },
    "answer": "C",
    "explanation": {
      "correct": "Supraclavicular lymph node involvement (N3) without distant visceral metastasis is Stage IIIC.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 66,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "The most frequent site of distant metastasis for breast cancer is:",
    "options": {
      "A": "Brain",
      "B": "Bone",
      "C": "Lung",
      "D": "Liver",
      "E": "Adrenal glands"
    },
    "answer": "B",
    "explanation": {
      "correct": "The skeleton (bone) is the most common site of distant spread for breast cancer.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 68,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "Breast cancer during pregnancy is:",
    "options": {
      "A": "Always a reason for termination",
      "B": "Never treated with chemotherapy",
      "C": "The most common cancer diagnosed during pregnancy",
      "D": "Always ER positive",
      "E": "Treated with radiation in the first trimester"
    },
    "answer": "C",
    "explanation": {
      "correct": "Breast cancer is the most common malignancy during pregnancy. Treatment depends on the trimester; chemotherapy can often be given safely in the 2nd and 3rd trimesters.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 69,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "Routine follow-up after breast cancer treatment should always include:",
    "options": {
      "A": "Monthly tumor markers",
      "B": "Quarterly CT scans",
      "C": "Yearly bone scans",
      "D": "Regular clinical exams and yearly mammography",
      "E": "Semi-annual MRI"
    },
    "answer": "D",
    "explanation": {
      "correct": "Evidence-based follow-up focuses on history, physical examination, and annual mammography to detect local recurrence or a new primary.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 70,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "Submuscular placement of breast implants is preferred because:",
    "options": {
      "A": "It is less painful.",
      "B": "It prevents all capsule formation.",
      "C": "It allows better mammographic visualization of breast tissue.",
      "D": "It is cheaper.",
      "E": "It eliminates the risk of rupture."
    },
    "answer": "C",
    "explanation": {
      "correct": "Placing implants behind the pectoral muscle makes it easier for radiologists to visualize native breast tissue during screening mammography.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 71,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "What is the incidence of breast cancer in males?",
    "options": {
      "A": "<1% of all breast cancers",
      "B": "5%",
      "C": "10%",
      "D": "20%",
      "E": "50%"
    },
    "answer": "A",
    "explanation": {
      "correct": "Male breast cancer is rare, representing less than 1% of the total breast cancer cases.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 73,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "A large breast tumor with skin erosion and a favorable outlook is likely:",
    "options": {
      "A": "Medullary carcinoma",
      "B": "Cystosarcoma phyllodes (benign)",
      "C": "Scirrhous carcinoma",
      "D": "Inflammatory carcinoma",
      "E": "Paget's disease"
    },
    "answer": "B",
    "explanation": {
      "correct": "Phyllodes tumors can grow quite large and even ulcerate the skin, but most are benign or low-grade and have an excellent prognosis with wide local excision.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  },
  {
    "id": 75,
    "specialty": "Breast Surgery",
    "topic": "Breast Disease",
    "question": "An 'occult' primary breast cancer typically presents as:",
    "options": {
      "A": "A large palpable mass",
      "B": "Nipple discharge only",
      "C": "Axillary lymphadenopathy with no visible breast mass",
      "D": "Bone pain",
      "E": "Skin rash"
    },
    "answer": "C",
    "explanation": {
      "correct": "Occult primary breast cancer presents as metastatic disease (usually in the axillary nodes) where the primary tumor in the breast cannot be identified by physical exam or standard imaging.",
      "A": "",
      "B": "",
      "C": "",
      "D": "",
      "E": ""
    },
    "guideline": "Surgery Clinical Cases MCQ's",
    "takeaway": "See explanation for key learning point."
  }
];
}
