// Auto-harvested from: Oncology MCQ.docx.txt
// Generated: 2026-05-07T13:30:42.850Z
// NOTE: Answers default to A — all questions need manual review.
// Specialty: General Surgery | Questions: 18
if (!window.QUESTIONS) window.QUESTIONS = [];
window.QUESTIONS.push(...[
  {
    "id": 9100,
    "specialty": "General Surgery",
    "topic": "General Surgery",
    "question": "Oncology MCQ 1. Cytotoxic T cells (CTL) are capable of recognizing:",
    "options": {
      "A": "Peptide antigens associated with major histocompatibility complex (MHC) molecules.",
      "B": "Membrane-bound antigens.",
      "C": "Cytoplasmic antigens.",
      "D": "Nuclear antigens.",
      "E": ""
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield General Surgery board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current General Surgery guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "General Surgery board principles",
    "takeaway": "Review Oncology MCQ 1. Cytotoxic T cells (CTL) are capable of recognizing:...",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  },
  {
    "id": 9101,
    "specialty": "General Surgery",
    "topic": "General Surgery",
    "question": "Nuclear antigens.E. All of the above.Answer: EDISCUSSION: It was long thought that CTL recognize antigen expressed on the surface of the target cell destined to be killed, similar to the recognition of an antigen by an antibody; however, it was found that the mechanism of CTL recognition of antigens was fundamentally different from the mechanism of antibody recognition. CTL can detect antigens derived from cell surface–associated proteins, but in addition can recognize proteins that are normally in the cytoplasm or in the nucleus. In fact, the normal location of the protein can be anywhere within the cell.To understand how a CTL can distinguish an antigen from a protein that is normally located within the cytoplasm or nucleus of the cell, investigators had to determine exactly what was being recognized by the CTL. T cells were found to recognize short linear fragments of processed or even denatured protein. It was found that proteins that were synthesized endogenously were degraded within the cytoplasm into 9– or 10–amino acid long peptides. These peptides were then transported to the endocytoplasmic reticulum and associated with newly synthesized MHC class I molecules. Certain peptides could fit within the MHC class I molecule and were then transported to the cell surface as a complex. It was this complex, consisting of a 9– to 10–amino acid peptide within a MHC class I molecule that was presented to, and recognized by, CD8+ CTL.2. Adoptive immunotherapy with lymphokine activated killer cells (LAK) and tumor infiltrate (TIL) cells are characterized by:",
    "options": {
      "A": "Nonspecific stimulation of effector cells.",
      "B": "Expansion ex vivo of large numbers of lymphocytes.",
      "C": "Infusion with interleukin 2 (IL-2).",
      "D": "Significant toxicity at high doses.",
      "E": ""
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield General Surgery board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current General Surgery guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "General Surgery board principles",
    "takeaway": "Review Nuclear antigens.E. All of the above.Answer: EDISCUSSION: It was long thought th...",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  },
  {
    "id": 9102,
    "specialty": "HPB",
    "topic": "HPB",
    "question": "Significant toxicity at high doses.E. All of the above.Answer: EDISCUSSION: LAK cells, generated by short-term culture of peripheral blood lymphocytes in the presence of high concentrations of IL-2, lyse transformed target cells, and have minimal lytic activity for most normal tissues. Up to 10 11 in vitro generated LAK cells have been administered in a single intravenous infusion to cancer patients. Therapeutic trials have also combined short courses of high-dose systemic IL-2 administration with LAK cell transfer to promote LAK function and viability, with apparently enhanced efficacy. The shortcomings of LAK and IL-2 therapy included a larger degree of toxicity (including pulmonary, renal, and hepatobiliary) with a significant proportion of patients requiring intensive care unit admissions and 2% to 5% treatment-related mortality. Despite this, response rate remained relatively low.Another therapy using in vitro expanded lymphocytes derived from a TIL has been evaluated in clinical trials. In humans, TIL cell lines have been generated by mincing tumor specimens and culturing eluted lymphocytes with high concentrations of IL-2. TIL lines can be expanded to 10 8 to 10 11 cells over 3 to 8 weeks in culture, and some lines appear to function as T cells with lytic specificity for autologous—but not allogeneic—tumor targets, whereas others function as LAK cells and lyse both autologous and allogeneic tumor targets. Adoptive transfer of 5 × 10 10 TIL alone has not been associated with significant toxicity, and administration of 5 × 10 10 TIL cells with concurrent systemic IL-2 has caused toxicities that are attributable to the IL-2.3. Previous clinical studies with cancer vaccines have:",
    "options": {
      "A": "Clearly demonstrated induction of tumor-specific immune response.",
      "B": "Repeatedly demonstrated clinical response to large tumor burden.",
      "C": "Not clearly demonstrated induction of tumor-specific immune response.",
      "D": "Not been performed to date.DISCUSSION: Several different approaches in experimental animal studies in the 1970s formed the basis for human clinical trials of SAI against human cancers. Although severa"
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield HPB board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current HPB guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "HPB board principles",
    "takeaway": "Review Significant toxicity at high doses.E. All of the above.Answer: EDISCUSSION: LAK ...",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  },
  {
    "id": 9103,
    "specialty": "General Surgery",
    "topic": "General Surgery",
    "question": "Not been performed to date.Answer: CDISCUSSION: Several different approaches in experimental animal studies in the 1970s formed the basis for human clinical trials of SAI against human cancers. Although several thousand patients have been injected with a variety of tumor cell preparations in this country and elsewhere during the past 25 years, the complexity of the studies has made it difficult to definitively assess the value of this approach to cancer therapy. Nonetheless, a number of clinical trials have suggested a therapeutic benefit of SAI. Most of these trials have two features in common: (1) a therapeutic effect was not seen or, if seen, has not been confirmed independently; and (2) no acceptable information was provided on the presence of tumor antigens in the vaccines and the immune response of patients to these antigens.4. Which of the following statements is/are true of the epidemiology and etiology of melanoma?",
    "options": {
      "A": "Most patients are diagnosed after age 60 years.",
      "B": "Skin color has no association with risk of melanoma.",
      "C": "Sun exposure is the only risk factor for melanoma.",
      "D": "The per capita incidence of melanoma is highest in Australia.DISCUSSION: The median age at diagnosis is in the late forties; so, a minority of patients are diagnosed after age 60. The risk of melanoma"
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield General Surgery board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current General Surgery guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "General Surgery board principles",
    "takeaway": "Review Not been performed to date.Answer: CDISCUSSION: Several different approaches in ...",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  },
  {
    "id": 9104,
    "specialty": "General Surgery",
    "topic": "General Surgery",
    "question": "The per capita incidence of melanoma is highest in Australia.Answer: DDISCUSSION: The median age at diagnosis is in the late forties; so, a minority of patients are diagnosed after age 60. The risk of melanoma is closely tied to skin color: Caucasians are at highest risk, and those with a Celtic complexion at even higher risk. Australia has a large Celtic population living near the equator, and it has the highest per capita incidence of melanoma in the world. Sun exposure is believed to be an important cause of melanoma, but the data remain incomplete. Some melanomas arise in sites not exposed to the sun (e.g., mucous membranes), so sun exposure is not the only risk factor.5. Which of the following variables best predicts prognosis for patients with a recent diagnosis of cutaneous melanoma and no clinical evidence of metastatic disease?",
    "options": {
      "A": "Breslow thickness.",
      "B": "Clark's level.",
      "C": "Ulceration.",
      "D": "Gender.",
      "E": ""
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield General Surgery board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current General Surgery guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "General Surgery board principles",
    "takeaway": "Review The per capita incidence of melanoma is highest in Australia.Answer: DDISCUSSION...",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  },
  {
    "id": 9105,
    "specialty": "Cardiothoracic",
    "topic": "Cardiothoracic",
    "question": "Gender.E. Celtic complexion.Answer: ADISCUSSION: The prognosis for melanoma is best predicted by the thickness, measured in millimeters (Breslow thickness). Clark's level and ulceration are also predictive, but less so. Gender is a secondary prognostic factor. Skin color may have a mild impact on outcome, but it is primarily a risk factor for developing melanoma.6. A 38-year-old man presents with a melanoma on the skin of the right calf measuring 5 mm. in thickness. Several large nodes are palpable in the right inguinal region. Which of the following statements about the appropriate management of this clinical problem is false?",
    "options": {
      "A": "In the absence of systemic disease, the primary melanoma of the right calf should be excised with at least a 2-cm. margin.",
      "B": "Complete right inguinal node dissection should be performed if there is no evidence of systemic metastasis.",
      "C": "If further work-up reveals multiple lung metastases of melanoma, they should be excised as soon as possible.",
      "D": "Chemotherapy for melanoma is primarily palliative; so surgical therapy is preferred if there is no evidence of metastatic disease beyond the inguinal region.",
      "E": ""
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield Cardiothoracic board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current Cardiothoracic guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "Cardiothoracic board principles",
    "takeaway": "Review Gender.E. Celtic complexion.Answer: ADISCUSSION: The prognosis for melanoma is b...",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  },
  {
    "id": 9106,
    "specialty": "Cardiothoracic",
    "topic": "Cardiothoracic",
    "question": "Chemotherapy for melanoma is primarily palliative; so surgical therapy is preferred if there is no evidence of metastatic disease beyond the inguinal region.E. If the nodes do not contain metastatic disease but are simply reactive, the chance of 5-year survival is 50% or less.Answer: CDISCUSSION: This patient should be evaluated with computed tomography in addition to a careful history, review of systems, and physical examination. If there is no evidence of metastatic disease beyond the inguinal region, therapy should focus on the local and regional disease. The primary lesion should be excised with a 2- to 3-cm. margin. The enlarged nodes can be evaluated by fine-needle aspiration (FNA) or node excision. If the FNA or excisional biopsy does show metastatic melanoma, then complete inguinal node dissection should be performed. Alternatively, complete node dissection can be justified simply on the basis of clinical findings. Chemotherapy does not provide any significant chance of cure, whereas a significant proportion of patients with isolated nodal metastases will live long. The depth of the primary lesion would predict chances of 5-year survival at less than 50%, even if the nodes are not metastatic. If work-up does reveal multiple pulmonary nodules, chemotherapy or experimental systemic therapies should be considered. Surgery has no role in the therapy of multiple lung metastases of melanoma.7. A 42-year-old woman presents with an 8 cm. × 6 cm. × 4 cm. mass in the posterior thigh. Incisional biopsy reveals a high-grade liposarcoma. Her management should include:",
    "options": {
      "A": "High thigh amputation.",
      "B": "Extracompartment excision with negative margins.",
      "C": "Complete excision with negative margins.",
      "D": "Adjuvant radiation therapy.",
      "E": ""
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield Cardiothoracic board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current Cardiothoracic guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "Cardiothoracic board principles",
    "takeaway": "Review Chemotherapy for melanoma is primarily palliative; so surgical therapy is prefer...",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  },
  {
    "id": 9107,
    "specialty": "General Surgery",
    "topic": "General Surgery",
    "question": "Adjuvant radiation therapy.E. Adjuvant chemotherapy.Answer: CDDISCUSSION: This is a common presentation of soft tissue sarcoma. Surgery remains the principal modality for curative therapy for all soft tissue sarcomas. Provided the entire tumor is removed, less radical procedures have not been demonstrated to adversely affect local recurrence or outcome. The surgical objective is complete removal of the tumor with negative margins and maximal preservation of function. Adjuvant radiation improves local control. Adjuvant chemotherapy has not proven to be efficacious.8. Biologic features of adult soft tissue sarcomas include the following:",
    "options": {
      "A": "Mutations of p53 in metastatic liposarcoma.",
      "B": "A low (less than 1%) risk of metastasis for small, low-grade lesions.",
      "C": "Recurrent disease in at least 33% of patients.",
      "D": "Lymph node metastasis in less than 3% of patients.",
      "E": ""
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield General Surgery board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current General Surgery guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "General Surgery board principles",
    "takeaway": "Review Adjuvant radiation therapy.E. Adjuvant chemotherapy.Answer: CDDISCUSSION: This i...",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  },
  {
    "id": 9108,
    "specialty": "General Surgery",
    "topic": "General Surgery",
    "question": "Lymph node metastasis in less than 3% of patients.E. Mutations of p53 in Li-Fraumeni syndrome.Answer: BCDEDISCUSSION: Inactivation of the p53 tumor suppressor gene is involved in tumorigenesis of several sarcomas, but not specifically liposarcoma. The relevance of this gene is underscored by the frequent occurrence of soft tissue sarcomas in the Li-Fraumeni syndrome, where all families studied have p53 germ line mutations. Low-grade lesions have a low (less than 1%) risk of subsequent metastasis, whereas high-grade lesions have a high (greater than 50%) risk of subsequent metastasis. Despite optimal multimodality treatment, at least 33% of patients develop recurrent disease (median disease-free interval 18 months). Lymph node metastasis occur in fewer than 3% of adult soft tissue sarcomas.9. Which of the following statements describes an ideal tumor marker?",
    "options": {
      "A": "The ideal tumor marker should be tumor specific; that is, in the normal population or patients with benign diseases, false-positive test results are rare.",
      "B": "The ideal marker must have a low false-negative rate; that means that all patients with a particular type of cancer should test positive.",
      "C": "The circulating level of an ideal tumor marker should correlate directly with the amount of viable tumor and be a measure of the response to therapy.",
      "D": "The ideal tumor marker should act as a prognostic indicator.",
      "E": ""
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield General Surgery board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current General Surgery guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "General Surgery board principles",
    "takeaway": "Review Lymph node metastasis in less than 3% of patients.E. Mutations of p53 in Li-Frau...",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  },
  {
    "id": 9109,
    "specialty": "HPB",
    "topic": "HPB",
    "question": "The ideal tumor marker should act as a prognostic indicator.E. All of the above.Answer: EDISCUSSION: Each of the above is a criterion for an ideal tumor marker.10. A marker for the diagnosis of pancreatic cancer is:",
    "options": {
      "A": "CA 15-3.",
      "B": "CA 19-9.",
      "C": "Alphafetoprotein (AFP).",
      "D": "Carcinoembryonic antigen (CEA).",
      "E": "CYFRA 21-1."
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield HPB board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current HPB guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "HPB board principles",
    "takeaway": "Review The ideal tumor marker should act as a prognostic indicator.E. All of the above....",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  },
  {
    "id": 9110,
    "specialty": "Urology",
    "topic": "Urology",
    "question": "Carcinoembryonic antigen (CEA).E. CYFRA 21-1.Answer: BDISCUSSION: CA 15-3 is a marker for breast cancer. AFP is a marker for hepatocellular and testicular cancer. CEA is a marker for colon cancer. CYFRA 21-1 is a marker for non–small-cell lung cancer. CA 19-9 is a marker for pancreatic cancer.11. Which of the following tumors may cause elevated CEA levels?",
    "options": {
      "A": "Breast cancer.",
      "B": "Colorectal cancer.",
      "C": "Gastric cancer.",
      "D": "Lung cancer.",
      "E": ""
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield Urology board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current Urology guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "Urology board principles",
    "takeaway": "Review Carcinoembryonic antigen (CEA).E. CYFRA 21-1.Answer: BDISCUSSION: CA 15-3 is a m...",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  },
  {
    "id": 9111,
    "specialty": "Cardiothoracic",
    "topic": "Cardiothoracic",
    "question": "Lung cancer.E. All of the above.Answer: EDISCUSSION: CEA is relatively nonspecific, and each of the listed cancers can cause elevated levels of CEA.12. The presence of which marker is a significant poor prognosis variable for patients with breast cancer:",
    "options": {
      "A": "CEA.",
      "B": "C-erb B-2.",
      "C": "AFP.",
      "D": "Human chorionic gonadotropin (hCG).",
      "E": "RB-1."
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield Cardiothoracic board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current Cardiothoracic guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "Cardiothoracic board principles",
    "takeaway": "Review Lung cancer.E. All of the above.Answer: EDISCUSSION: CEA is relatively nonspecif...",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  },
  {
    "id": 9112,
    "specialty": "Breast & Endocrine",
    "topic": "Breast & Endocrine",
    "question": "Human chorionic gonadotropin (hCG).E. RB-1.Answer: BDISCUSSION: Some 20% to 30% of breast cancers have C-erb B-2 gene expression. Studies have demonstrated that it is an independent prognostic tumor marker. Tumors that express C-erb B-2 have a poorer prognosis.13. The most useful circulating marker for patients with hepatocellular carcinoma is:",
    "options": {
      "A": "CA 50.",
      "B": "Levels of vitamin B 12.",
      "C": "CEA.",
      "D": "AFP.",
      "E": "hCG."
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield Breast & Endocrine board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current Breast & Endocrine guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "Breast & Endocrine board principles",
    "takeaway": "Review Human chorionic gonadotropin (hCG).E. RB-1.Answer: BDISCUSSION: Some 20% to 30% ...",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  },
  {
    "id": 9113,
    "specialty": "Colorectal",
    "topic": "Colorectal",
    "question": "AFP.E. hCG.Answer: DDISCUSSION: Eighty percent of patients with hepatocellular carcinoma have elevated serum levels of AFP.14. In patients with colorectal cancer the serum CEA level is a clinically useful measure for all reasons except:",
    "options": {
      "A": "Prognosis.",
      "B": "Detection of recurrence.",
      "C": "Guiding second-look operations.",
      "D": "Following treatment response.",
      "E": ""
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield Colorectal board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current Colorectal guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "Colorectal board principles",
    "takeaway": "Review AFP.E. hCG.Answer: DDISCUSSION: Eighty percent of patients with hepatocellular c...",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  },
  {
    "id": 9114,
    "specialty": "Urology",
    "topic": "Urology",
    "question": "Following treatment response.E. Early diagnosis.Answer: EDISCUSSION: CEA levels may be used for each of the indications except early diagnosis.15. Which serum markers are useful in the management of patients with testicular cancer?",
    "options": {
      "A": "hCG.",
      "B": "AFP.",
      "C": "CA 15-3.",
      "D": "Two of the above.",
      "E": ""
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield Urology board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current Urology guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "Urology board principles",
    "takeaway": "Review Following treatment response.E. Early diagnosis.Answer: EDISCUSSION: CEA levels ...",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  },
  {
    "id": 9115,
    "specialty": "Urology",
    "topic": "Urology",
    "question": "Two of the above.E. None of the above.Answer: DDISCUSSION: AFP and hCG are useful in managing testicular cancer. Approximately 90% of patients with testicular cancer have elevated levels of one or both of these markers.16. Which tumor marker is useful for the management of patients with breast cancer?",
    "options": {
      "A": "CA 125.",
      "B": "Inhibin.",
      "C": "CA 19-9.",
      "D": "CA 15-3.",
      "E": "CEA."
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield Urology board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current Urology guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "Urology board principles",
    "takeaway": "Review Two of the above.E. None of the above.Answer: DDISCUSSION: AFP and hCG are usefu...",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  },
  {
    "id": 9116,
    "specialty": "Cardiothoracic",
    "topic": "Cardiothoracic",
    "question": "CA 15-3.E. CEA.Answer: DDISCUSSION: CA 15-3 is the only useful marker for patients with breast cancer. Approximately 73% of patients with breast cancer have elevated levels.17. A new marker that has possible utility in the management of patients with non–small-cell lung cancer (NSCLC) is:",
    "options": {
      "A": "Calcitonin.",
      "B": "Neuron-specific enolase.",
      "C": "CYFRA 21-1.",
      "D": "Glucagon.",
      "E": ""
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield Cardiothoracic board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current Cardiothoracic guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "Cardiothoracic board principles",
    "takeaway": "Review CA 15-3.E. CEA.Answer: DDISCUSSION: CA 15-3 is the only useful marker for patien...",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  },
  {
    "id": 9117,
    "specialty": "Cardiothoracic",
    "topic": "Cardiothoracic",
    "question": "Glucagon.E. Chromogranin A.Answer: CDISCUSSION: CYFRA 21-1 is a new marker for non–small-cell lung cancer (NSCLC). Approximately 40% to 50% of patients with NSCLC will have elevated levels.18. A circulating marker that may be useful in the management of patients with any neuroendocrine tumor is:",
    "options": {
      "A": "Chromogranin A.",
      "B": "Neuron-specific enolase.",
      "C": "hCG.",
      "D": "Two of the above.",
      "E": ""
    },
    "answer": "A",
    "sharp": {
      "S": "High-yield Cardiothoracic board question.",
      "H": "Review each option carefully against the clinical stem.",
      "A": "Eliminate options that don't fit the primary diagnosis or guideline principle.",
      "R": "Refer to current Cardiothoracic guidelines for this topic.",
      "P": "Remember the key fact and apply it to similar clinical scenarios."
    },
    "guideline": "Cardiothoracic board principles",
    "takeaway": "Review Glucagon.E. Chromogranin A.Answer: CDISCUSSION: CYFRA 21-1 is a new marker for n...",
    "source_tag": "Oncology MCQ.docx.txt",
    "needs_review": true
  }
]);
