// Auto-generated by SHARP 3.0 Markdown Pipeline
if(typeof window !== "undefined") {
  window.QUESTIONS = window.QUESTIONS || [];
  window.QUESTIONS.push(...[
{
  "source_file": "good ortho mcq exam_2 conv.docx",
  "id": 90646,
  "specialty": "Orthopedics",
  "topic": "good ortho mcq exam_2 conv.docx",
  "question": "Autonomous bladder:",
  "options": {
    "A": "it follows transection of sacral segments of cord or cauda equina.",
    "B": "periodic emptying of bladder is dependent upon a local reflex in the bladder wall.",
    "C": "abdominal straining and compression of abdominal wall will induce reflex of bladder emptying.",
    "D": "recovery is common if the cauda lesion is neurapraxia or axontemesis."
  },
  "answer": "A",
  "markdown_debrief": "Failed to generate Markdown."
}
]);
